# Generated by Django 5.2.4 on 2025-07-25 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField()),
                ('korean_translation', models.TextField(blank=True)),
                ('tts_service_used', models.CharField(blank=True, max_length=20)),
                ('voice_speed_used', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_count', models.IntegerField(default=1)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevenlabs_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('groq_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_voice_speed', models.CharField(choices=[('fast', 'Fast'), ('normal', 'Normal'), ('slow', 'Slow')], default='normal', max_length=10)),
                ('preferred_tts_service', models.CharField(choices=[('browser', 'Browser TTS'), ('google', 'Google TTS'), ('elevenlabs', 'ElevenLabs AI')], default='google', max_length=20)),
                ('daily_character_usage', models.IntegerField(default=0)),
                ('last_usage_date', models.DateField(auto_now=True)),
                ('total_characters_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
