# Generated by Django 5.2.4 on 2025-07-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_translate_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
