# Generated by Django 5.2.4 on 2025-07-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_google_translate_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_translation_service',
            field=models.CharField(choices=[('auto', 'Auto (Best Available)'), ('groq', 'Groq AI'), ('google', 'Google Translate'), ('basic', 'Basic Dictionary')], default='auto', max_length=20),
        ),
    ]
