# Generated by Django 5.2.4 on 2025-07-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_preferred_translation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_tts_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_tts_service',
            field=models.CharField(choices=[('browser', 'Browser TTS'), ('google', 'Google TTS (Free)'), ('google_cloud', 'Google Cloud TTS'), ('elevenlabs', 'ElevenLabs AI')], default='google', max_length=20),
        ),
    ]
