# Generated by Django 5.2.4 on 2025-07-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_google_tts_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhistory',
            name='target_language',
            field=models.CharField(default='ko', max_length=10),
        ),
    ]
