# Generated by Django 5.2.4 on 2025-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studyhistory_target_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhistory',
            name='source_language',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
